"""empty message

Revision ID: 6fe3354c2b
Revises: None
Create Date: 2015-03-01 12:03:23.116664

"""

# revision identifiers, used by Alembic.
revision = '6fe3354c2b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', postgresql.JSON(), nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recommendation')
    op.drop_table('image')
    op.drop_table('facebook')
    op.drop_table('search')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('radius', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agefrom', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ageto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('facebook_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('fromdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('todate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('facebook',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='facebook_pkey')
    )
    op.create_table('image',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_id', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('recommendation',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastmatched', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_table('results')
    ### end Alembic commands ###
